name: ny_auth_slate
description: Slate package to quickly scaffold a login + register system.
version: 0.4.2
repository: https://github.com/nylo-core/ny_auth_slate
homepage: https://nylo.dev

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  nylo_support: ^5.36.0
  flutter:
    sdk: flutter
  args: ^2.4.2
  collection: ^1.16.0

dev_dependencies:
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter: